services:
  chat-rs-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres

volumes:
  db:
    

